# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
name: CI

on:
  push: ~

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          # Note: Use quotes to avoid float cast - especially important if the
          # version number ends with 0!
          - "3.12"

    steps:
      - name: Clone repo
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          # https://github.com/actions/setup-python#caching-packages-dependencies
          cache: pipenv
          python-version: ${{ matrix.python-version }}
      - name: Install build dependencies
        # https://stackoverflow.com/a/5178444/5568265
        # https://stackoverflow.com/a/58002908/5568265
        run: |
          sudo apt-get install libxml2-dev libxslt-dev
      - name: Install dependencies
        run: |
          python -m pip install pipenv
          pipenv install --dev
      - name: List files
        run: ls src/**/*.py test/**/*.py
      - name: Run black
        run: pipenv run black --check src/**/*.py test/**/*.py
      - name: Run pylint
        run: pipenv run pylint src/**/*.py test/**/*.py
      - name: Run ruff
        run: pipenv run ruff check src/**/*.py test/**/*.py
      - name: Run tests
        run: pipenv run pytest
